openapi: 3.0.3
info:
  title: Logistic Engine Base Project
  version: '1.0'
  description: Seed Project for Logistic Engine Solutions
servers:
  - url: '/api/v1'
paths:
  /demo:
    get:
      tags:
        - 'Demo'
      summary: demo endpoint
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DemoResponse'
              example:
                products:
                  [
                    { id: 'string', price: 1500, quantity: 1 },
                    { id: 'string', price: 1500, quantity: 2 },
                  ]
  /demo/another:
    get:
      tags:
        - 'Demo'
      summary: demo endpoint to get another response
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DemoResponse'
              example:
                products:
                  [
                    { id: 'string', price: 1500, quantity: 1 },
                    { id: 'string', price: 1500, quantity: 2 },
                  ]
components:
  schemas:
    DemoResponse:
      properties:
        products:
          type: array
          items:
            $ref: '#/components/schemas/Product'
    Product:
      properties:
        id:
          type: string
        price:
          type: number
        quantity:
          type: integer
