swagger: "2.0"
info:
  version: 1.0.0
  title: rest-typescript
  description: ripley-app
basePath: /api/v1
tags:
  - name: Ripley
    description: Simple example endpoints
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json

definitions:
  RipleyBody:
    type: object
    title: example
    required:
      - name
    properties:
      name:
        type: string
        example: no_stress
paths:
  /ripley/consultaPendientesConfirmacion:
    post:
      tags:
        - Ripley
      consumes:
        - application/json
      parameters:
        - in: body
          name: consultaPendientesConfirmacion
          required: true
          schema:
            type: object
       # - name: request
       #  in: path
       # required: true
       #description: The id of the example to retrieve
       #type: integer
      responses:
        200:
          description: Return the example with the specified id
        404:
          description: Example not found



  /ripley:
    get:
      tags:
        - Ripley
      description: Fetch all examples
      responses:
        200:
          description: Returns all examples
        500:
          description: Internal server error



    post:
      tags:
        - Ripley
      description: Create a new example
      parameters:
        - name: example
          in: body
          description: an example
          required: true
          schema: 
            $ref: "#/definitions/RipleyBody"
      responses:
        200:
          description: Returns all examples

  /ripley/{id}:
    get:
      tags:
        - Ripley
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the example to retrieve
          type: integer
      responses:
        200:
          description: Return the example with the specified id
        404:
          description: Example not found



  
  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification

